### ISSUE TITLE
Delete endpoint for admin views

### ISSUE THREAD

**Issue by Jelcoo** [BlueprintFramework/framework#53] opened 2024-08-20 15:07 UTC
### Current Behavior

Currently there is no delete endpoint for the admin views, only get, patch and post.

### Expected Behavior

I would like to have a delete endpoint as well, so I can delete data with a matching endpoint (instead of hacking together a post request).

### Steps to Reproduce

-

### Blueprint Version

beta-2024-07

### Panel Version

1.11.7

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details and tested my reproduction steps.
- [X] I have checked to my best capabilities and believe this is a bug with the software, and not a configuration issue with my specific system.
- [X] I have made sure to check that this bug is the fault of Blueprint and is not caused by stock Pterodactyl.

**Comment by itsvic-dev** [comment] 2024-08-20 21:46
this should probably get marked as a feature request and not a bug

**Closed** 2024-08-22 14:57 UTC
Labels: enhancement
